global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksandr_strekalov'
