version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USERNAME}/ui:${UIVER}
    ports:
      - ${HOSTPORT}:${CONTPORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POSTVER}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${COMMENTVER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
    ipam:
        config:
          - subnet: 10.0.2.0/24
  back_net:
    ipam:
        config:
          - subnet: 10.0.1.0/24
